spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
